# Schema for the configuration files of the custom_form module.
custom_form.settings:
  type: config_object
  label: 'custom_form settings'
  mapping:
    example:
      type: string
      label: 'Example'
