# Schema for the configuration files of the config_prepopulate module.
config_prepopulate.settings:
  type: config_object
  label: 'config_prepopulate settings'
  mapping:
    example:
      type: string
      label: 'Example'
