config_prepopulate.settings_form:
  path: '/admin/config/system/config-prepopulate'
  defaults:
    _title: 'config_prepopulate settings'
    _form: 'Drupal\config_prepopulate\Form\SettingsForm'
  requirements:
    _permission: 'administer config_prepopulate configuration'
